/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xtron;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Juegos
 */
public class Xtron_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Xtron_GUI
     */
    public boolean compila;
    int name;

    public Xtron_GUI() {
        this.setResizable(false);

        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        name = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btn_compile = new javax.swing.JButton();
        btn_run = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComandos = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTAREA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        TXFACUMULADOR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TXATUTORIAL = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_compile.setText("DEBUG");
        btn_compile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compileActionPerformed(evt);
            }
        });

        btn_run.setText("RUN");
        btn_run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_runActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        txtComandos.setColumns(20);
        txtComandos.setRows(5);
        jScrollPane2.setViewportView(txtComandos);

        TXTAREA.setColumns(20);
        TXTAREA.setRows(5);
        jScrollPane1.setViewportView(TXTAREA);

        jLabel1.setText("COMPILE STATE");

        jButton3.setText("LOAD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TXFACUMULADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXFACUMULADORActionPerformed(evt);
            }
        });

        jLabel2.setText("ACUMULADOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_compile)
                                        .addComponent(btn_save)
                                        .addComponent(btn_run))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(20, 20, 20))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(TXFACUMULADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_compile)
                .addGap(35, 35, 35)
                .addComponent(btn_run)
                .addGap(48, 48, 48)
                .addComponent(btn_save)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXFACUMULADOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("FILE", jPanel1);

        TXATUTORIAL.setColumns(20);
        TXATUTORIAL.setRows(5);
        jScrollPane3.setViewportView(TXATUTORIAL);

        jButton1.setText("VER TUTORIAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CREDITOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1)
                        .addGap(69, 69, 69)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TUTORIAL", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.TXATUTORIAL.setText("CREDITOS\nIgnacio Monge Valverde  B34396 \nAgustin Camacho Mora B2302");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.TXATUTORIAL.setText("ESTE ES UN TUTORIAL CON LAS OPERACIONES BASICAS QUE REALIZA LA MAQUINA XTRON\n\n\n"
                + "CODIGO DE OPERACION                             SIGNIFICADO\n\n"
                + "READ  10                                         "
                + "                     Lee una palabra desde el teclado y la introduce"
                + "en una ubicacion especifica de memoria\n\n"
                + "WRITE 11 ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        String save = "";
        String comandos = txtComandos.getText();
        String lineas[] = comandos.split("\n");
        for (int i = 0; i < lineas.length - 1; i++) {
            save += lineas[i] + "\r\n";
        }
        Xtron_IO saves = new Xtron_IO();
        try {
            if (save != "") {
                saves.guardarArchivo("file" + name + ".txt", save);
                name++;
                JOptionPane.showMessageDialog(null, "SE HA GUARDADO CON EXITO");
            } else {
                JOptionPane.showMessageDialog(null, "NO HAY COMANDOS PARA GUARDAR");
            }

        } catch (IOException ex) {
            Logger.getLogger(Xtron_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private String[] compile() {
        TXTAREA.setText(null);
        String comandos = txtComandos.getText();
        String lineas[] = comandos.split("\n");
        String separar = "";
        String act = "";
        boolean caso = true;
        int line = 0;
        String[] vecMemory = new String[100];
        for (int i = 0; i < lineas.length; i++) {
            vecMemory[i] = lineas[i];
        }
          Xtron_Cpu xtron = new Xtron_Cpu();

        for (int i = 0; i < lineas.length; i++) {
            separar = lineas[i];
            char[] charArray = separar.toCharArray();

            act = lineas[i];
            if (act.matches("[0-9]+") == false) {
                line = i + 1;
                TXTAREA.append("ERROR. El comando en la linea " + line + " solo debe tener numeros\n");
                TXTAREA.setLineWrap(true);
                compila = false;
                caso = false;

            } else {
                if (charArray.length != 4) {
                    line = i + 1;

                    TXTAREA.append("ERROR. LA DIMENSION DEL COMANDO EN LA LINEA " + line + " ES INCORRECTA\n");
                    TXTAREA.setLineWrap(true);
                    compila = false;
                    caso = false;
                } else {

                    line = i + 1;
                    // JOptionPane.showMessageDialog(null,"LA COMPILACION EN LA LINEA  "+line+" SE REALIZO CON EXITO");
//                    TXTAREA.append("LA COMPILACION EN LA LINEA  " + line + " SE REALIZO CON EXITO\n");
//                    TXTAREA.setLineWrap(true);
                    caso = true;
                }
              
                try {
                    vecMemory = xtron.CPU_Debuger(vecMemory, i,lineas.length);
                    convertirMatriz(vecMemory, (int) Math.sqrt(vecMemory.length));
                    TXFACUMULADOR.setText(xtron.getAcumulator()+"");
                    if(xtron.getCiclo()==true || xtron.getTerminateProgram()==true){
                        break;
                    }

                } catch (Xtron_Exeption ex) {
                    TXTAREA.append(ex.getMessage()+"\n");
                    TXTAREA.setLineWrap(true);
                }

            }

        }

        return lineas;
    }
    private void btn_runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_runActionPerformed
        Xtron_Cpu correr = new Xtron_Cpu();
        String[] vec = compile();
        String mem = "";
        String[] vecMemory = new String[100];
        try {
            vecMemory = correr.CPU_Run(vec);
            TXFACUMULADOR.setText(correr.getAcumulator() + "");

            // TODO add your handling code here:
        } catch (Xtron_Exeption ex) {
            TXTAREA.append(ex.getMessage() + "\n");
            TXTAREA.setLineWrap(true);

        }

        for (int i = 0; i < vecMemory.length - 1; i++) {
            mem += "" + vecMemory[i] + "\n";

        }
        JOptionPane.showMessageDialog(null, vecMemory.length);
      //  convertirMatriz(vecMemory, (int) Math.sqrt(vecMemory.length));
//        convertirMatriz(vecMemory,10);
        JOptionPane.showMessageDialog(null, mem);
    }//GEN-LAST:event_btn_runActionPerformed

    private void convertirMatriz(String[] vec, int n) {
        int cont = 0;
        String mat = "";
        String[][] matriz = new String[n][n];
        for (int x = 0; x < n; x++) {
            for (int y = 0; y < n; y++) {
                matriz[y][x] = vec[cont];

                cont++;

            }
        }
        for (int x = 0; x < n; x++) {
            mat += "\n";
            for (int y = 0; y < n; y++) {
                if (matriz[y][x] == null) {
                    mat += "+0000" + "     ";
                } else {
                    mat += "+" + matriz[y][x] + "     ";
                }
            }
        }
        JOptionPane.showMessageDialog(null, mat);

    }
    private void btn_compileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compileActionPerformed
        // TODO add your handling code here:

        compile();

    }//GEN-LAST:event_btn_compileActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        JFileChooser chooser = new JFileChooser();
//chooser.setApproveButtonText("Abrir TxT");
//chooser.addChoosableFileFilter(new TxTFilter());
//chooser.showOpenDialog(null);
//File archivo=chooser.getSelectedFile();
        txtComandos.setText(null);
        TXTAREA.setText(null);
        JFileChooser chooser = new JFileChooser();
        chooser.setApproveButtonText("Abrir TxT");
        chooser.addChoosableFileFilter(new TxTFilter());
        chooser.showOpenDialog(null);
        File archivo = chooser.getSelectedFile();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(archivo));
            String linea = reader.readLine();
            while (linea != null) {
                txtComandos.append(linea + "\n");
                linea = reader.readLine();
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TXFACUMULADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXFACUMULADORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXFACUMULADORActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Xtron_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Xtron_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Xtron_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Xtron_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Xtron_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TXATUTORIAL;
    private javax.swing.JTextField TXFACUMULADOR;
    private javax.swing.JTextArea TXTAREA;
    private javax.swing.JButton btn_compile;
    private javax.swing.JButton btn_run;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtComandos;
    // End of variables declaration//GEN-END:variables
}
